#!/usr/bin/env node
/* Capture only the current candidate and compare it with the immutable visual bundle. */
const fs=require('fs');const path=require('path');const crypto=require('crypto');const {spawnSync}=require('child_process');
const {launchChromium,contextOptions,installNetworkSandbox,installRuntimeInstrumentation,environmentFingerprint,isExpectedSandboxConsole}=require('./browser');
function arg(name,fallback=null){const i=process.argv.indexOf(`--${name}`);return i>=0?process.argv[i+1]:fallback;}
function toUrl(value){if(/^https?:\/\//.test(value)||/^file:/.test(value))return value;return 'file://'+path.resolve(value).replace(/\\/g,'/');}
function load(value,fallback){return value?JSON.parse(fs.readFileSync(value,'utf8')):fallback;}
function sha(value){return crypto.createHash('sha256').update(value).digest('hex');}
async function main(){
  const candidate=arg('candidate'),contractPath=path.resolve(arg('contract')||''),outDir=path.resolve(arg('out-dir','h2d-transfer-output'));if(!candidate||!arg('contract'))throw new Error('Usage: --candidate --contract --out-dir');
  const contract=load(contractPath,{});const bundlePath=path.resolve(path.dirname(contractPath),contract.reference_bundle.path);const bundle=load(bundlePath,{});const visualPath=path.join(path.dirname(bundlePath),'visual_reference_manifest.json');const visual=load(visualPath,{});
  if(sha(fs.readFileSync(bundlePath))!==contract.reference_bundle.sha256)throw new Error('reference bundle hash mismatch');if(visual.donor_identity!==bundle.donor_identity)throw new Error('visual manifest donor identity mismatch');
  const requestRules=load(arg('request-allowlist'),[]);const regions=load(arg('critical-regions'),[]);const masks=load(arg('deviation-paint-masks'),[]);const rows=[];const issues=[];fs.mkdirSync(path.join(outDir,'screenshots'),{recursive:true});fs.mkdirSync(path.join(outDir,'reports'),{recursive:true});
  const referenceRows=new Map((visual.rows||[]).map(row=>[row.matrix_key,row]));const threshold=Number(arg('max-pixel-mismatch-ratio','0.005'));
  for(const profile of contract.browser_profiles||[]){const browser=await launchChromium({headless:profile.headless!==false,projectRoot:arg('project-root')||process.cwd()});try{for(const viewport of contract.responsive_matrix||[]){
    const key=`${viewport.width}x${viewport.height}@${profile.id}`;const reference=referenceRows.get(key);if(!reference){issues.push(`${key}: frozen reference missing`);continue;}
    const context=await browser.newContext(contextOptions(profile,viewport));await installNetworkSandbox(context,requestRules);await installRuntimeInstrumentation(context);const page=await context.newPage();const runtimeErrors=[];page.on('pageerror',error=>runtimeErrors.push(String(error.message||error).slice(0,300)));page.on('console',message=>{if(message.type()==='error'&&!isExpectedSandboxConsole(message))runtimeErrors.push(message.text().slice(0,300));});await page.goto(toUrl(candidate),{waitUntil:'networkidle'});await page.waitForTimeout(Number(arg('settle-ms','250')));
    const candidateFile=path.join(outDir,'screenshots',`candidate_${key.replace(/[^a-z0-9_.-]/gi,'_')}.png`);await page.screenshot({path:candidateFile,fullPage:true});const env=await environmentFingerprint(browser,context,page);const envHash=sha(Buffer.from(JSON.stringify(env)));const referenceFile=path.resolve(path.dirname(bundlePath),reference.screenshot);const diffFile=path.join(outDir,'screenshots',`diff_${key.replace(/[^a-z0-9_.-]/gi,'_')}.png`);
    const regionFile=path.join(outDir,'reports',`.regions_${key.replace(/[^a-z0-9_.-]/gi,'_')}.json`);const maskFile=path.join(outDir,'reports',`.masks_${key.replace(/[^a-z0-9_.-]/gi,'_')}.json`);fs.writeFileSync(regionFile,JSON.stringify(regions.filter(row=>row.matrix_key===key)));fs.writeFileSync(maskFile,JSON.stringify(masks.filter(row=>row.matrix_key===key)));
    const result=spawnSync(arg('python','python'),[path.join(__dirname,'image_diff_metrics.py'),referenceFile,candidateFile,'--diff',diffFile,'--regions',regionFile,'--masks',maskFile],{encoding:'utf8'});fs.unlinkSync(regionFile);fs.unlinkSync(maskFile);if(result.status!==0)throw new Error(result.stderr||result.stdout||'image diff failed');const metrics=JSON.parse(result.stdout);const regionFailure=(metrics.regions||[]).some(row=>row.result!=='pass');const environmentMatch=envHash===reference.environment_sha256;const pass=metrics.pixel_mismatch_ratio<=threshold&&!regionFailure&&environmentMatch&&!runtimeErrors.length;if(!pass)issues.push(`${key}: visual/environment/runtime mismatch`);
    rows.push({matrix_key:key,reference:reference.screenshot,candidate:path.relative(outDir,candidateFile).replace(/\\/g,'/'),diff:path.relative(outDir,diffFile).replace(/\\/g,'/'),pixel_mismatch_ratio:metrics.pixel_mismatch_ratio,critical_regions:metrics.regions,environment_match:environmentMatch,runtime_errors:runtimeErrors,verdict:pass?'pass':'fail'});await context.close();
  }}finally{await browser.close();}}
  const result=issues.length?'fail':'pass';const report={result,schema_version:'2.0',reference_bundle_sha256:contract.reference_bundle.sha256,matrix_keys:rows.map(row=>row.matrix_key).sort(),viewports:rows,issues};fs.writeFileSync(path.join(outDir,'reports','diff_summary.json'),JSON.stringify(report,null,2));console.log(`result=${result} matrix=${rows.length} issues=${issues.length}`);if(result!=='pass')process.exitCode=2;
}
main().catch(error=>{console.error(error.stack||error);process.exit(1);});
